'use client'

import Sidenav from "@/components/Sidenav";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function Dashboard({ children }) {
  return (
    <div className="flex h-screen">
      <main className="flex-1 overflow-auto">
        <Sidenav />
        {children}
      </main>
    </div>
  );
}
